const createBoard = () => {
  const tableArea = document.createElement('div');
  const tableLeft = document.createElement('div');
  const tableRight = document.createElement('div');
  const titleLeft = document.createElement('div');
  const titleRecent = document.createElement('h1');
  const btnRefresh = document.createElement('button');
  const scoresArea = document.createElement('div');
  const scoresList = document.createElement('ul');
  const titleAdd = document.createElement('h1');
  const formAddScore = document.createElement('form');
  const inputName = document.createElement('input');
  const inputScore = document.createElement('input');
  const addBtn = document.createElement('input');
  tableArea.setAttribute('id', 'board');
  tableArea.setAttribute('class', 'f-row');
  tableLeft.setAttribute('class', 'f-col');
  tableLeft.setAttribute('id', 'left-col');
  tableRight.setAttribute('class', 'f-col');
  tableRight.setAttribute('id', 'right-col');
  titleLeft.setAttribute('class', 'f-col');
  titleLeft.setAttribute('id', 'left');
  btnRefresh.innerHTML = 'Refresh';
  btnRefresh.setAttribute('id', 'refresh');
  titleRecent.innerHTML = 'Recent Scores';
  scoresArea.setAttribute('class', 'f-col');
  scoresArea.setAttribute('id', 'allScores');
  scoresList.setAttribute('id', 'scores-list');
  titleAdd.innerHTML = 'Add your score';
  formAddScore.setAttribute('id', 'addScoreForm');
  formAddScore.setAttribute('class', 'f-col');
  inputName.setAttribute('type', 'text');
  inputName.setAttribute('name', 'yourName');
  inputName.setAttribute('id', 'name');
  inputName.setAttribute('placeholder', 'You\'re name')
  inputScore.setAttribute('type', 'text');
  inputScore.setAttribute('name', 'yourScore');
  inputScore.setAttribute('placeholder', 'You\'re score');
  inputScore.setAttribute('id', 'score');
  addBtn.setAttribute('type', 'submit');
  addBtn.setAttribute('value', 'Submit');
  addBtn.setAttribute('id', 'add-btn');
  formAddScore.append(inputName, inputScore, addBtn);
  titleLeft.append(titleRecent, btnRefresh);
  scoresArea.appendChild(scoresList);
  tableLeft.append(titleLeft, scoresArea);
  tableRight.append(titleAdd, formAddScore);
  tableArea.append(tableLeft, tableRight);
  return tableArea;
};

export default createBoard;
